### ISSUE TITLE
hijack gives a strange issue at times.

### ISSUE THREAD

**Issue by c4ftabrez** [ileitch/hijack#12]
Hi,
I get an error about mirror process every time I start hjak.  I have to either reinstall the gem or to run the update to make the gem work.

details of the error:

/Users/xxxxxxxx/.rvm/gems/ruby-1.9.2-p290/gems/hijack-0.2.0/lib/hijack/console.rb:52:in `mirror_process': undefined method`-' for nil:NilClass (NoMethodError)
    from /Users/shaikhtabrez/.rvm/gems/ruby-1.9.2-p290/gems/hijack-0.2.0/lib/hijack/console.rb:15:in `initialize'
    from /Users/shaikhtabrez/.rvm/gems/ruby-1.9.2-p290/gems/hijack-0.2.0/lib/hijack.rb:18:in`new'
    from /Users/shaikhtabrez/.rvm/gems/ruby-1.9.2-p290/gems/hijack-0.2.0/lib/hijack.rb:18:in `start'
    from /Users/shaikhtabrez/.rvm/gems/ruby-1.9.2-p290/gems/hijack-0.2.0/bin/hijack:27:in`<top (required)>'
    from /Users/shaikhtabrez/.rvm/gems/ruby-1.9.2-p290/bin/hijack:19:in `load'
    from /Users/shaikhtabrez/.rvm/gems/ruby-1.9.2-p290/bin/hijack:19:in`<main>'
~/xxxx>bundle update hijack
Fetching gem metadata from http://rubygems.org/.^C

Actually, today it has stopped working with the update too.  Las time I did a full uninstall and an update.  Any suggestions?

**Comment by c4ftabrez** [comment]
I am getting this error now: 
=> Hijacking...
=> Tried 3 times to attach to 58083 whilst GC wasn't running but failed.
=> This means either the process calls GC.start frequently or GC runs are slow - try hijacking again.

**Comment by ileitch** [comment]
Please try 0.2.1.

**Comment by c4ftabrez** [comment]
Thanks ileitch!  It works now!
