### ISSUE TITLE
Can't hijack Rails 3 process running under Ruby 1.9.2 

### ISSUE THREAD

**Issue by dolzenko** [ileitch/hijack#9]
Here is the output I get running `hijack --gdb-debug` command on Rails 3/Ruby 1.9.2 process:

<pre><code>
...
> #50 0x08167afc in vm_exec (th=0x8430740) at vm.c:1132
> #51 0x08167e44 in rb_iseq_eval_main (iseqval=138667220) at vm.c:1373
> #52 0x0805dfa2 in ruby_exec_internal (n=0x843e4d4) at eval.c:204
> #53 0x0805f8e2 in ruby_run_node (n=0x843e4d4) at eval.c:251
> #54 0x0805d370 in main (argc=3, argv=0xbffc7c44) at main.c:35
(gdb) set variable (int)rb_trap_pending=1
> No symbol "rb_trap_pending" in current context.
(gdb) break rb_trap_exec
> Function "rb_trap_exec" not defined.
> Make breakpoint pending on future shared library load? (y or [n]) [answered N; input not from terminal]
(gdb) continue
</code></pre>

Obviously nothing happens afterwards.

PS. It looks like `rb_trap_exec` was removed in this commit
http://redmine.ruby-lang.org/repositories/diff/ruby-19/signal.c?rev=19080

**Comment by ileitch** [comment]
Hi thanks for letting me know, I've not tested against 1.9 yet, I'll try have a look soon.

**Comment by ileitch** [comment]
Please try 0.2.1.
